### ISSUE TITLE
Original "implies" symbol still present

### ISSUE THREAD

**Issue by MGBergweiler** [mdnahas/Peano_Book#3]
The original circular "deducitur" symbol is still present instead of its modern equivalent "right arrow" once on page 20 of the pdf, section "Remarks." on the last line of the page ("the form α Cβ, where α and β are propositions..."), and twice in the continuation of that paragraph on the start of the next page.

**Comment by mdnahas** [comment]
Thank you, @MGBergweiler!   

Closed by commit:
https://github.com/mdnahas/Peano_Book/commit/46e27bdb5aed51c078ad99e5a78d134fd2a0c3ca
