### ISSUE TITLE
Symbols (), [], {} never defined as grouping symbols

### ISSUE THREAD

**Issue by MGBergweiler** [mdnahas/Peano_Book#4]
On section "I. Punctuation.", page 8 of the pdf, the passage containing:

"we use parentheses, as in algebra"

is greyed out, meaning it is irrelevant, although the symbols used there, (), [], {}, where never defined in its new usage as grouping symbols. Since the original work and also this translation is nicely "self contained" (any new usage of a symbol is defined), I would have added a red note with something like: "To aid visualisation, the precedence grouping of symbols is according to the traditional use of parentheses, brackets and braces like in algebra, instead of only parentheses."

**Comment by mdnahas** [comment]
I understand your point.  But by translating it into traditional math, I think it implies the traditional use of parentheses.  I don't think we'll lose readers by not saying anything.
